### ISSUE TITLE
Commit command no longer saves the lock under certain circumstances

### ISSUE THREAD

**Issue by troshko111** [nilslice/protolock#107]
This change https://github.com/nilslice/protolock/commit/7c9188151bdf1b4015ccf397a7eb32dbd7287941#diff-57de67624b47e4a29ab98fbcc5904d81
introduced a bug when `commit` is used with `force` set to `false` (the default).

Previously committing an empty `json` proto lock would generate the proper proto lock file, now it does nothing.

Root cause:

```go
	case "commit":
		// if force option is false (default), then disallow commit if
		// there are any warnings encountered by runing a status check.
		if !*force {
			status(cfg) // <-- this currently always exits on all code paths.
		}

		r, err := protolock.Commit(*cfg)
		if err != nil {
			fmt.Println(err)
			os.Exit(1)
		}

		err = saveToLockFile(*cfg, r) // <-- never reached even if there were no warnings.
		if err != nil {
			fmt.Println(err)
			os.Exit(1)
		}
```

Since the linked change, `status` always exits the process and this never reaches `saveToLockFile` _even if there were no warnings_.

Breaking change was the unconditional exit at the end of the `status` function with the code from the refactored `handleReport`, previously the `status` would only exit on non-zero.

I suggest the behavior is reverted.

**Comment by nilslice** [comment]
@troshko111 - yes, thank you for reporting! There is a fix up at #106 to revert this. If you could, check it out and verify (as I have done) -- it would be helpful! I can merge and release immediately after your input.

**Comment by troshko111** [comment]
I'd be happy to verify, but can't find the binary artifact on that circle job for the PR.

**Comment by troshko111** [comment]
Oh I see you already released, trying.

**Comment by nilslice** [comment]
@troshko111 - yes, sorry, due to the serious break I felt I should release the fix as soon as I had any confirmation (which @evanlknapp provided). If you find that there is still anything incorrect with the CLI behavior, please let me know 👍 Thanks!

**Comment by nilslice** [comment]
> I'd be happy to verify, but can't find the binary artifact on that circle job for the PR.

:) soon, there will be a real release process... these releases are currently build by me running `./release.sh` from this repo, cross-compiled for various arch/OS, and uploaded to the release page. 

If you have experience with these kind of automated release processes, it would be a great way to contribute to this project!

**Comment by troshko111** [comment]
Looks good to me (at least as far as the commit of an empty json file behavior, it's back to what it was).

Thanks for the prompt fix!
