### ISSUE TITLE
Cannot parse certain Protobuf files

### ISSUE THREAD

**Issue by lihalite** [nilslice/protolock#108]
Definitions like the following fail to parse:

https://github.com/googleapis/googleapis/blob/316b54c401ab9bc08ed71cb362915b9e7a23bb05/google/ads/googleads/v0/common/ad_type_infos.proto#L127-L129

The underlying issue is in https://github.com/emicklei/proto, which doesn't expect that a type name can have spaces. (Perhaps this is a quirk of the official Protobuf implementation.)

**Comment by nilslice** [comment]
This is an interesting one! I'll see if there is an update to patch from emicklei/proto (possible we're on an older version of the library), or otherwise I can open an issue on that repo.

**Comment by lihalite** [comment]
Looks like it got fixed: https://github.com/emicklei/proto/issues/111

**Comment by nilslice** [comment]
Excellent -- I'll update the deps and cut a new release ASAP. Thanks!

**Comment by nilslice** [comment]
New release available: https://github.com/nilslice/protolock/releases/tag/v0.13.0

**Comment by lihalite** [comment]
Thanks for the quick turnaround!
