### ISSUE TITLE
Deterministic definition order.

### ISSUE THREAD

**Issue by thespags** [nilslice/protolock#110]
For readability it would be nice if the  proto paths would sorted alphabetically

```
{
  "definitions": [
    {
      "protopath": "fub:/:baz:/:some_proto.proto",
     ....
    },
   {
      "protopath": "other:/:foo:/:other_proto.proto",
   {
  ]
}
```

**Comment by nilslice** [comment]
Hey @thespags - 

Are you on the latest version? I believe this was introduced a couple releases ago.

**Comment by thespags** [comment]
Let me upgrade the version and try it out. I'll update and close if that's the fix. Thanks!

**Comment by rmichela** [comment]
I upgraded the maven protolock plugin to use 0.12.0. https://github.com/salesforce/proto-backwards-compat-maven-plugin/pull/4

**Comment by thespags** [comment]
After upgrading to 0.12.0 we are seeing deterministic ordering based on the name. Looks good thanks!
