### ISSUE TITLE
What are the differences to Uber‘s Prototool

### ISSUE THREAD

**Issue by Fleshgrinder** [nilslice/protolock#112]
As a potential user I ask myself what the differences are to [Uber‘s Prototool](https://github.com/uber/prototool) which seems to be easier to use because it doesn‘t require the management of a lock file.

**Comment by nilslice** [comment]
Prototool added support for backward compatibility checks recently, but I have not used it. I'm sure it's a great tool which offers _many_ more features than just compatibility. If you're already using it for compilation, and whatever else, I'd assume you can feel good sticking with it for compatibility checks too. 

One thing `protolock` does that `prototool` seems to not support, is the use of [your own plugins](https://github.com/nilslice/protolock/wiki/Plugins) to add proto checks in addition to the base ones included. 

I'd do your own homework though and see how they work with your codebase and workflow.
