### ISSUE TITLE
Lock file does not record aggregate options with array values

### ISSUE THREAD

**Issue by rmichela** [nilslice/protolock#117]
### Reproduction

1. Construct a [message with a field with a compound option with an array value](https://github.com/envoyproxy/protoc-gen-validate/blob/master/tests/harness/cases/numbers.proto#L10).
```proto
message FloatIn { float val = 1 [(validate.rules).float = {in: [4.56, 7.89]}]; }
```
2. Run `protolock init`
3. Inspect `proto.lock`

### Expected
* Lock file tracks option values

### Actual
* Lock file tracks option presence and name, but value is missing.
```json
          {
            "name": "FloatIn",
            "fields": [
              {
                "id": 1,
                "name": "val",
                "type": "float",
                "options": [
                  {
                    "name": "(validate.rules).float",
                    "aggregated": [
                      {
                        "name": "in"
                      }
                    ]
                  }
                ]
              }
            ]
          },
```

**Comment by nilslice** [comment]
Thanks for reporting, @rmichela - do you have a fix in mind or had this just popped up and you're looking for help? 

I believe @aroch provided this feature, so maybe if we ask nicely :smile: he can take a look! Otherwise, I will have to carve out some time next week to dig in.

**Comment by rmichela** [comment]
I don't have a fix in mind (yet). The issue came up while developing a protolock plugin for protoc-gen-validate. PGV makes heavy use of compound options.

**Comment by aroch** [comment]
You're correct, I did not support compound options. I started working on a fix, but will need a bit more time to finalise and create a PR.
