### ISSUE TITLE
Nested messages conflicts

### ISSUE THREAD

**Issue by celrenheit** [nilslice/protolock#12]
Hello,

I think there is an issue when using nested messages that have the same name. The following example should trigger a conflict:

```proto
syntax = "proto3";

package main;

message A {
    message I {
        int32 index = 1;
    }

    string id = 1;
    I i = 2;
}

message B {
    message I {
        int32 index = 1;
    }

    string id = 1;
    I i = 2;
}
```

This gives me the following error:
```
➜  protolock init
➜  protolock status
CONFLICT: "I" is re-using ID: 1, a reserved field [main.proto]
CONFLICT: "I" is re-using name: "index", a reserved field [main.proto]
```

**Comment by nilslice** [comment]
Interesting -- thank you for reporting! This is definitely a bug. I will need to update the tests to contain nested messages. Can I ask, what did you expect the output to be? 

You mention: 
> The following example should trigger a conflict:

What would you expect the conflict to be?

**Comment by celrenheit** [comment]
I expected it to not have a conflict

**Comment by nilslice** [comment]
@celrenheit - ok, perfect, that's what I figured but was confused (should vs. shouldn't in your comment). 

Is this something you'd like to try fixing? No problem if not, just didn't want to duplicate efforts. 
Thanks again!

**Comment by celrenheit** [comment]
Yep sorry for the confusion.
I'll try to have a look into it whenever I have time

**Comment by nilslice** [comment]
@celrenheit - would you please try #16? I believe it should fix this issue.

**Comment by nilslice** [comment]
I've tested this internally enough to feel confident in the fix. @celrenheit - I'm going to merge, but if you get around to it, please update your binary and test as well. I'd would appreciate it!

**Comment by celrenheit** [comment]
This fixed the issue but by ignoring nested messages.
I've submitted PR #17 which also checks to not reuse reserved fields in nested messages.
