### ISSUE TITLE
Error building protolock on ppc64le

### ISSUE THREAD

**Issue by rashmi-ibm** [nilslice/protolock#125]
The below error appears when I try to build protolock repo on a ppc64le system.

Error:-
bash-4.4# go get -u github.com/nilslice/protolock/...
github.com/nilslice/protolock/cmd/protolock
/root/go/src/github.com/nilslice/protolock/cmd/protolock/plugins.go:147:20: undefined: strings.ReplaceAll
bash-4.4# 

go version go1.9.1 linux/ppc64le

Need to generate the protolock file. Inputs around the issue would be of help.

**Comment by nilslice** [comment]
@rashmi-ibm Can you install a more recent version of Go? Ideally you'd build protolock from the latest Go (go1.13), but you could use go1.12, which [introduced the `strings.ReplaceAll` func](https://golang.org/pkg/strings/#ReplaceAll).

**Comment by nilslice** [comment]
or use Docker, by building an image with something like: 

```dockerfile
FROM ppc64le/golang:alpine3.10 as build
ENV GO111MODULE on
ENV CGO_ENABLED 0
RUN mkdir -p /out/usr/bin
WORKDIR /protolock
COPY . .
RUN go test -v ./...
RUN go build -o protolock ./cmd/protolock/*.go
RUN cp protolock /out/usr/bin/protolock

FROM ppc64le/alpine:3.10
COPY --from=build /out/ .
ENTRYPOINT ["/usr/bin/protolock"]
```

This exact script isn't working for me, but something similar may on the `ppc64le` target.
