### ISSUE TITLE
Does protolock support proto2 ?

### ISSUE THREAD

**Issue by doudoutinghua** [nilslice/protolock#128]
when I remove a required field from the following file, protolock status is ok.

`syntax = "proto2";

message IdCard {
    reserved 1;
    reserved "id";
    //required string id = 1;
    required string name = 2;
    optional string addr = 3;
    required string log = 4;
}
`

**Comment by nilslice** [comment]
The underlying proto parser supports Proto2, but `protolock` itself is not tested for any Proto2 support. I wouldn't count on it -- sorry!
