### ISSUE TITLE
Propose to publish ARM64 binary in releases

### ISSUE THREAD

**Issue by liusheng** [nilslice/protolock#129]
Hi there, I would like to propose to publish `ARM64/aarch64` specific arch binaries in protolock releases.  I have tried to make other projects such as Alluxio running on ARM64 server, because it depend on `protolock` (loaded by `proto-backwards-compat-maven-plugin` maven plugin) while `protolock` does not have ARM64 binary in releases.  I have tried manually compiling `protolock` on my ARM64 server, everything looks OK, So is there possible to also publish protolock binary for ARM64 platform ?

FYI:
Alluxio ARM support issue: https://github.com/Alluxio/alluxio/issues/12704
proto-backwards-compat-maven-plugin ARM support issue: https://github.com/salesforce/proto-backwards-compat-maven-plugin/pull/21

Thanks.

**Comment by nilslice** [comment]
Hi @liusheng - thanks for bringing this to my attention! 

I would be happy to cut a new release that includes the additional target. I don't have the free cycles right now to modify & test the builds, but if you need this soon and can help, I'd suggest taking a look at the [`release.sh`](https://github.com/nilslice/protolock/blob/master/release.sh) script. There, you'll likely need to add a new target arch, but may also need to modify how the `build` function works a bit.

**Comment by liusheng** [comment]
Hi @nilslice  Thank for quickly reply and support for this proposal.
I have tried compiling protolock on my ARM64 server by simple `go get -u github.com/nilslice/protolock/...`, everything looks OK, the `protolock` binary can be successfully compiled and can executed. According to your above suggestion, I have also tried modifying the `release.sh` by adding a line of `build linux arm64` on a x86 server with Ubuntu 18.04+go1.15.2,  the arm binary can be also sucessfully generated, then I have also copied it to ARM server and verified. But it seems the `windows` and `darwin` os + `arm64` arch still have support issues. see:
```
cmd/go: unsupported GOOS/GOARCH pair windows/arm64
tar: protolock.exe: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

```
So maybe for now we can only support `linux`+`arm64` now as it is common usage ?

**Comment by nilslice** [comment]
@liusheng that sounds like a good plan, as I don't think Go has support for windows on arm64 yet: https://github.com/golang/go/issues/36439

I will review your PR and cut a release including the new build, then ping you here once it can be downloaded from the release page. It would be helpful if you could test that the binary works after downloaded.

Thanks!

**Comment by nilslice** [comment]
@liusheng, please find the `arm64` build on the latest release: https://github.com/nilslice/protolock/releases/tag/v0.15.1

If you are able to, confirm that the build works for you. Much appreciated! I will close this issue for now, but please re-open if you have any problems.

**Comment by liusheng** [comment]
Hi @nilslice , Thank you for so quick release! Yes, I have just confirmed the arm64 binary in newest release on ARM server, everything is OK. thank you.

**Comment by nilslice** [comment]
Great, thanks again!
