### ISSUE TITLE
[.gitignore] Remove "protolock" line or edit file to not filter out "cmd/protolock"

### ISSUE THREAD

**Issue by antoine-dbr** [nilslice/protolock#149]
This line https://github.com/nilslice/protolock/blob/master/.gitignore#L1 is probably here to make sure the exe is not being accidentally commited. However, it masks out the cmd/protolock dir from Mercurial and as a result fail to properly import the files under cmd/protolock in our source control. Could this be fixed? TIA!

**Comment by nilslice** [comment]
Sorry about that -- this is now fixed!
