### ISSUE TITLE
Embedded comments confuse the parser

### ISSUE THREAD

**Issue by zack-littke-smith** [nilslice/protolock#154]
In a proto file like:
```
message Example {
  optional /* i'm a comment */ bool field = 1;
}
```

We would see a produced lock:
```
{
  "type": "/* i'm a comment */",
  "optional": true,
},
{
  "id": 1,
  "name": "field",
  "type": "bool"
}
```

But would expect:
```
{
  "id": 1,
  "name": "field",
  "type": "bool",
  "optional": true
}
```

As if the comment didn't exist.

**Comment by nilslice** [comment]
great catch & thanks for the report.. this might require a fix in the upstream parser but I will investigate asap!

**Comment by zack-littke-smith** [comment]
@nilslice found a related issue in https://github.com/emicklei/proto/issues/131 where the author closed as 'unlikely,' I think it should be their responsibility to fix this issue.

**Comment by zack-littke-smith** [comment]
They are adding support in https://github.com/emicklei/proto/issues/131

**Comment by nilslice** [comment]
@zack-littke-smith - oh, great!

if you're watching that PR, do you want to open one on Protolock once it lands with the updated dependency version?

If you do, a adding this style of comment into one of the existing tests would also be good to prove it's working as expected.

**Comment by zack-littke-smith** [comment]
Happy to!

**Comment by zack-littke-smith** [comment]
This is fixed in `github.com/emicklei/proto v1.13.2`, I can fork this repo and PR this but this is new territory for me, may be faster if you opened against yourself.

**Comment by nilslice** [comment]
@zack-littke-smith here's a PR that updates the parser library and adds a test for this behavior. Let me know if this works for you!

https://github.com/nilslice/protolock/pull/158

I'll include this in the next release.
