### ISSUE TITLE
Duplicate message names with different fields are considered valid

### ISSUE THREAD

**Issue by ratangsenapathy** [nilslice/protolock#157]
If you declare two messages with the same name, but unique field names and field numbers, protolock does not detect any issues
For example:
```
message TestMessage {
  int32 Field1 = 1;
  int32 Field2 = 2;
}

message TestMessage {
  int32 Field3 = 3;
}
```

is considered as valid protobuf. Even though the "Enforced Rules" list doesn't explicitly mention this case, it seems like an imporatant consideration.

**Comment by nilslice** [comment]
@ratangsenapathy - thanks for bringing this up, but I think this should be handled by `protoc`, right? meaning, this is really more of a concern of your schema than compatibility. does `protoc` compile this? if it does, which `TestMessage` does it consider the one to generate code from? 

I'm not opposed to making a rule for this (or as always, you can make a plugin to check for duplicate messages) -- but in my opinion, this isn't really valid protobuf, and not within the scope of `protolock`'s goals. 

Perhaps we can as some other active users.. @pdecks, @zack-littke-smith, any thoughts on this?

**Comment by ratangsenapathy** [comment]
You are right on that front. It should be handled by protoc. Thank you I was combining two different concerns before.

**Comment by nilslice** [comment]
Ok, sounds good! Thank you for bringing this up though. Always open to new ways of keeping proto code compatible.
