### ISSUE TITLE
Include architecture in asset names in https://github.com/nilslice/protolock/releases

### ISSUE THREAD

**Issue by noel-yap** [nilslice/protolock#21]
Could the architecture be added to the asset names in https://github.com/nilslice/protolock/releases so it's more obvious whether or not they can be used as is? It might also make sense to be consistent with `${GOOS}` and `${GOARCH}` (eg `darwin` rather than `macos`).

**Comment by nilslice** [comment]
They sure can - that's a good idea. Take a look at the `release.sh` - that's where the names would be defined.

**Comment by noel-yap** [comment]
Can you review https://github.com/nilslice/protolock/pull/23?

**Comment by nilslice** [comment]
@noel-yap - yes, I will check it out by end of day today! thanks for submitting this

**Comment by nilslice** [comment]
Fixed in #24.
