### ISSUE TITLE
Weird flag parser

### ISSUE THREAD

**Issue by utrack** [nilslice/protolock#44]
Hi, just found out about the project - that's a neat tool!
I've just tried to add it to our Makefile and encountered a problem with flag parser.
Command `protolock --ignore=vendor status` seems to be parsed as
```
protolock
ignore="vendor status"
```
It looks like a bug to me esp since `ignore` should be comma-delimited.
`--ignore="vendor" status` behaves like that as well.

**Comment by nilslice** [comment]
Hey @utrack -

Did you try using comma-separatee values in the ignore option? i.e.

`protolock status --ignore=""`

**Comment by nilslice** [comment]
Sorry for the close & reopen of the issue. I'm on mobile at the moment 😁

**Comment by utrack** [comment]
No problem :)
Yeah, I've tried it and it works as a workaround.

**Comment by nilslice** [comment]
Ok great. Please note that this is intended behavior. The ignore flag is part of the options flagset which isn't parsed until the subcommand is.
