### ISSUE TITLE
Absolute fully qualified packages incorrectly produces empty `{}` block in `proto.lock` file.

### ISSUE THREAD

**Issue by november-yankee** [nilslice/protolock#59]
```bash
$ cat aoeu.proto
syntax = "proto3";

package com.example.aoeu;

import "snth.proto";

service AoeuService {
  rpc Method (Request) returns(Empty);
}

message Request {
  .example.snth.Field field1 = 1;
  .example.snth.Field field2 = 2;
}
$ cat snth.proto
syntax = "proto3";

package example.snth;

message Field {}
```

`protolock init` will produce:
```
$ cat proto.lock
…
                        "name": "Request",
                        "fields": [
                            {
                                
                            },
                            {
                                "id": 1,
                                "name": "field1",
                                "type": "example.snth.Field"
                            },
                            {
                                
                            },
                            {
                                "id": 2,
                                "name": "field2",
                                "type": "example.snth.Field"
                            }
                        ]
…
```

Upon `protolock status`, the empty `{}` blocks will error with:
```
CONFLICT: "Request" is re-using ID: 0, a reserved field number [src/main/proto/aoeu.proto]
CONFLICT: "Request" is re-using name: "", a reserved field name [src/main/proto/aoeu.proto]
```

**Comment by nilslice** [comment]
@november-yankee - interesting, thanks for reporting!

I think this has to do with the parser, which recently added support for these "dot"-prefixed names:
https://github.com/emicklei/proto/commit/31ca1a37608053a92355be293b13f08fe25e526e

We're building with `v1.6.4`, maybe an upgrade will fix... what do you think? 

Btw, I'm working on plugin support so `protolock` users can add their own rules in any language, similar to `protoc` code gen plugins. Could I ping you for a review?

**Comment by november-yankee** [comment]
Sure, ping me for a review but just to let you know, I'm less than a noob with Golang.

**Comment by nilslice** [comment]
Ha! No review is too small :) 

Also, being a Java user, it would be great to get your feedback on how the plugin development process would work.

I've added a Go package `protolock/extend` to make it easy for Go developers to make a plugin (all it really does is read JSON from stdin, do processing on protolock objects, and write JSON to stdout)..

**Comment by nilslice** [comment]
@november-yankee, #60 has a fix. Do you typically build this from source? I can upload a binary for you to try out, so you don't need to muck with the modules stuff.. let me know what platform you need it built for if that's preferable.

**Comment by nilslice** [comment]
[Archive.zip](https://github.com/nilslice/protolock/files/2540249/Archive.zip)

^ Contains the tarballs of all platforms w/ usually release

**Comment by nilslice** [comment]
This was just merged to master and I will cut a new release later this morning.

**Comment by november-yankee** [comment]
Thanks. Sorry for not reviewing.
