### ISSUE TITLE
Add support for Field Options

### ISSUE THREAD

**Issue by aroch** [nilslice/protolock#69]
We would like to use protolock with plugins which would validate specific field options.
I saw that Message Options are supported, but couldn't find support for Field Options.
Are there any plans to add support for Field Options to be saved also in the proto.lock file?
If not and you like the feature, we would be glad to implement and contribute.

**Comment by nilslice** [comment]
@aroch - the Field Option support is not currently planned, but if you'd like to PR it would be happily welcomed!

Note that @milton0825 implemented the Message Option feature (see [here](https://github.com/nilslice/protolock/pull/61/files)), and may be able to offer some direction if need be. Please don't hesitate to reach out to me as well if you have any questions. 

We have been pretty diligent with tests per feature added and would like to keep this up. If you have any questions about what to test or how, also please reach out. Looking at the existing test sets for an idea of where to start may help too (see [here](https://github.com/nilslice/protolock/blob/master/parse_test.go)). 

Thank you!

P.S. if you are interested and able to open source your plugin once it's complete, I'd be happy to feature it via link from the README. Also, let me know if you have any issues with development -- plugins are still a pretty new feature 👍

**Comment by aroch** [comment]
fixed by #71
