### ISSUE TITLE
commit command doesn't run plugins

### ISSUE THREAD

**Issue by aroch** [nilslice/protolock#76]
If --force option is not used, the 'commit' command runs 'status' before doing the commit.
If the user uses plugins as part of the 'status' command (with the --plugins option), I think he would expect that the same plugins would be run as part of the 'commit' command with same plugins option, so no validation is missed.

**Comment by nilslice** [comment]
Hey @aroch - do you think that it is a bug for plugins to be run for commit (with or without --force) or expected behavior? 

Let me know what you think the correct behavior is and we can figure out a solution. Thanks!

**Comment by aroch** [comment]
I think that if as part of the commit command you run the status part internally and fail if any warnings appear, then if the -plugins flag is passed for both status and commit, it should be taken into account.
Currently, the -plugins flag is ignored during commit but not during status. I think the expected behavior should be to run the plugins also during commit. 
What do you think?
