### ISSUE TITLE
gRPC Conf talk mention: collaborators, companies, use-cases, etc

### ISSUE THREAD

**Issue by nilslice** [nilslice/protolock#93]
Hey -- excited to share that [I'll be speaking about `protolock` at the first gRPC Conf](https://twitter.com/nilslice/status/1093956581602013194)! I wanted to mention the support and many contributions made from community members and if possible, the companies using the tool and if you have plugins or workflow use cases that could be briefly mentioned as well. 

If you're open to it, please either comment here or add your company/link to the [Related Users & Projects](https://github.com/nilslice/protolock#related-projects--users) section of the README 👍 as well as comments on this thread with any detail at all about your team/projects/workflows/plugins etc related to `protolock`. I'd really like to  highlight the work done by contributors and how you all have significantly improved the tooling.

cc: @wikiwong @celrenheit @btc @jeffmendoza @aroch @november-yankee @milton0825 @evanlknapp @mmmveggies

Thanks!

**Comment by nilslice** [comment]
_(sorry to abuse the issue tracker like this -- not sure of a better way to contact you all)_

**Comment by november-yankee** [comment]
Netflix uses it and have created a Gradle plugin for it (although it's not
open-sourced).
