### ISSUE TITLE
Add Support for Entry Level Options

### ISSUE THREAD

**Issue by evanlknapp** [nilslice/protolock#99]
I am looking to add options at a file (Entry) level in protolock.  A lot of our protobuf files resemble the following:

```
syntax = "proto3";

package test.package.v1;

import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

option java_multiple_files = true;
option java_package = "com.test.package.v1";
option java_outer_classname = "TestProto";

service MyService {
 ...
}

message MyMessage {
 ...
}
```

In addition to general protobuf file options my workplace has custom options that are also used at a file  level.  We'd like to add rules to makes sure in our custom plugin that options don't change. Would this be something we can add to protolock.

**Comment by nilslice** [comment]
Hey @evanlknapp - yes, this can definitely be added. Do you have bandwidth to consider a PR for it?

Thanks!

**Comment by evanlknapp** [comment]
Yes definitely. I will work on it and get a PR to you soon.

**Comment by evanlknapp** [comment]
@nilslice my PR is ready for review on #103

**Comment by evanlknapp** [comment]
@nilslice thanks for merging my PR. There is no super rush but when convenient it would be nice to get a release so I can take advantage of my fix from a while back and this enhancement. Thanks!

**Comment by nilslice** [comment]
@evanlknapp - you bet! just need to get a minor update added in too, which I'd like to get in the same release. Should be up by EOD at the latest.

**Comment by nilslice** [comment]
@evanlknapp, btw - I'd like to make this the last release which requires me to manually intervene after a new tag is added to the repo. If you're interested, I'll open an issue to track the work involved in automating releases using something like https://goreleaser.com/ - your feedback on how your integration process is done, and any contributions if interested, would be greatly appreciated!

**Comment by nilslice** [comment]
@evanlknapp - v0.11.0 has been released 👍

**Comment by evanlknapp** [comment]
@nilslice thanks a lot! As for doing some work into automating the release process, I cannot promise anything at this point. But I can try and look into it my spare time. I was looking into goreleaser and it looks promising.

**Comment by nilslice** [comment]
@evanlknapp  - no worries! just hoping to come to a working process that covers 99% of folks' needs. 

also, I released a quick patch for the latest... use v0.11.1 instead... sorry about that!
